# Generated by Django 5.2.6 on 2025-09-08 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Phone/Video Screening'), ('interview', 'Interview'), ('technical', 'Technical Assessment'), ('final', 'Final Round'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('applied_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
